### ISSUE TITLE
publish new version

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/string_decoder#1]
so we don't have 2 versions of safe-buffer with readable-stream

**Comment by mcollina** [comment]
I've added you to npm repo, so you can do a release.

**Comment by calvinmetcalf** [comment]
is it ok the tests don't pass curently

**Comment by mcollina** [comment]
they were when I released
Il giorno gio 22 giu 2017 alle 20:12 Calvin Metcalf <
notifications@github.com> ha scritto:

**Comment by calvinmetcalf** [comment]
ah they pass in node 6 but not 8, this goes for our version of string
decoder and the one in node, so this isn't a regression persay so I'll
publish it
